### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by marcogoldin** [Dataninja/fb_group#7]
Ho provato a lanciare lo script senza un limite di data. Dopo una ventina di minuti, arrivato a agosto 2016: 

`raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))`

che sia il caso di impostare un time.sleep() o un timeout?

**Comment by jenkin** [comment]
Mah, non mi sono chiari i limiti delle API di Facebook... per tirar giù tutto il nostro gruppo (fino a metà 2015) la prima volta ha dato l'errore che dici tu, la seconda volta ha fatto tutto senza problemi (ma più lentamente)... ha girato quasi un'ora senza interruzioni.

Bisogna approfondire i limiti e ovviamente gestire seriamente le eccezioni... :)
